### ISSUE TITLE
Color border on iTerm2

### ISSUE THREAD

**Issue by phuongtailtranminh** [josuegaleas/jay#1]
Hi,

I'm getting the problem with theme on iTerm2. It shows the blue border on left, right and bottom. How can I remove it?

<img width="1440" alt="screen shot 2016-10-08 at 1 12 18 am" src="https://cloud.githubusercontent.com/assets/12473996/19200639/4f1df728-8cf4-11e6-9df0-d0160d150c0c.png">

**Comment by phuongtailtranminh** [comment]
nvm,

I fixed it by changed the background color of iterm2 (Cmd + I -> Tab: Color) into the same as vim background

<img width="1440" alt="screen shot 2016-10-08 at 1 20 46 am" src="https://cloud.githubusercontent.com/assets/12473996/19200898/8d2276d8-8cf5-11e6-8928-926d03ef87e2.png">

**Comment by josuegaleas** [comment]
I'm glad you were able to solve the issue. I personally don't use iTerm 2, but please let me know if you run into any other issues. Thanks!
