### ISSUE TITLE
Make a transparent version

### ISSUE THREAD

**Issue by tjbcg** [josuegaleas/jay#3]
I'm thinking this theme could come with a transparent version (I've made one, see my fork).
There is not much to be changed, actually.
Also, in my vimrc: 
```vim
" Use soft dividers instead of hard ones
let g:airline_left_sep=''
let g:airline_right_sep=''
" Transparent background
hi Normal guibg=NONE ctermbg=NONE
hi Statement guibg=NONE ctermbg=NONE
hi Title guibg=NONE ctermbg=NONE
hi Todo guibg=NONE ctermbg=NONE
hi Underlined guibg=NONE ctermbg=NONE
hi ErrorMsg guibg=NONE ctermbg=NONE
hi LineNr guibg=NONE ctermbg=NONE
hi SignColumn guibg=NONE ctermbg=NONE
set background=dark
" Set airline colorscheme
let g:airline_theme='jay'
colorscheme jay
```

Which results in something like this:
(normal)
![normal](https://i.imgur.com/ggKvGlX.jpg)
(insert)
![insert](https://i.imgur.com/ZCEoTkq.jpg)
(visual)
![visual](https://i.imgur.com/z7vTwVW.jpg)

Th bottom line on these is tmux, hence not part of the transparent theme for vim.

Also, I made [this](https://gist.github.com/FliiFe/267ca9e774143437f8596a0b4b731869) a while back and never thought of publishing it. It might operate as a replacement for iTerm profile. As you might notice, I have commented out `color_background`and its application. Simply uncommenting these lines would restore the background color in the terminal.

If you pick things there and there from my repo/gist, don't give me credit, I don't need it ;-)

**Comment by josuegaleas** [comment]
This actually doesn't look bad! I'll definitely include it in the next update, probably after I'm done with classes.

**Comment by josuegaleas** [comment]
Took a while, but it's finally done! Starting from this [commit](https://github.com/josuegaleas/jay/commit/af1233c950149a496d4bedae5191d52334f3486c), there is now a transparent option.
