### ISSUE TITLE
Applying the colorscheme sets background=light

### ISSUE THREAD

**Issue by tjbcg** [josuegaleas/jay#4]
After upgrading to the new transparent version, I noticed Airline used the light palette.

I tested in an isolated environment using this minimal configuration.
```vim
call plug#begin('~/.vim/plugged')
Plug 'josuegaleas/jay'
call plug#end()

set background=dark
let jay_transparent = 1
colorscheme jay
```

After launching vim and doing `set background?`, vim show `background=light`.

Note that using `set background=light` keeps the light background, and that the transparent option doesn't change this behavior

**Comment by CryDeTaan** [comment]
I had the same problem, it seems moving `set background=dark` to the end fixed it for me.

Although, I am not using the `let jay_transparent = 1` option.

**Comment by tjbcg** [comment]
Yup, re-applying the background setting does indeed work. But this shouldn't be considered a fix.

**Comment by tjbcg** [comment]
Update: This is not a fix. While the airline theme works this way, the colorscheme ends up messed up (e.g. blue comments).

Using an autocommand seems to be a better workaround, but it removes all the colors in tabline (wtf?).

Trying an even more minimal configuration gives same results.
```vim
syntax on
set background=dark
colorscheme jay
```
with `jay.vim` in `.vim/colors/`.

After investigating putting debug messages (almost) everywhere in the file, I found that the change was caused by this specific line (and only this one)
```vim
call s:HF('Normal', s:fore, s:back)
```

The docs say
```
							*:hi-normal-cterm*
	When setting the "ctermfg" or "ctermbg" colors for the Normal group,
	these will become the colors used for the non-highlighted text.
	Example: >
		:highlight Normal ctermfg=grey ctermbg=darkblue
 	When setting the "ctermbg" color for the Normal group, the
	'background' option will be adjusted automatically.  This causes the
	highlight groups that depend on 'background' to change!  This means
	you should set the colors for Normal first, before setting other
	colors.
	When a colorscheme is being used, changing 'background' causes it to
	be reloaded, which may reset all colors (including Normal).  First
	delete the "g:colors_name" variable when you don't want this.
```

I could not manage to change this by unsetting `g:colors_name`, but here's a patch you can apply with `git apply`.
```patch
diff --git a/colors/jay.vim b/colors/jay.vim
index 81bc5df..73aca87 100644
--- a/colors/jay.vim
+++ b/colors/jay.vim
@@ -12,6 +12,8 @@ if exists("syntax_on")
 	syntax reset
 endif
 
+let s:original_background = &background
+
 let g:colors_name = "jay"
 
 if exists("jay_transparent")
@@ -201,6 +203,7 @@ call s:HF('Cursor', s:back, s:fore)
 call s:HF('lCursor', s:back, s:fore)
 call s:HF('MatchParen', s:back, s:orange, s:bold)
 call s:HF('Normal', s:fore, s:back)
+let &background = s:original_background
 call s:HF('Comment', s:back4)
 call s:HF('Constant', s:purple)
 call s:HF('Special', s:aqua)
@@ -268,6 +271,7 @@ if s:transparent == 1
 	call s:HF('lCursor', s:none, s:fore)
 	call s:HF('MatchParen', s:back, s:orange, s:bold) "FIXME
 	call s:HF('Normal', s:fore, s:none)
+    let &background = s:original_background
 	call s:HF('Error', s:red, s:none, s:bold)
 	call s:HF('Todo', s:fore0, s:none, s:bold)
 endif
```

**Comment by josuegaleas** [comment]
Are you guys using GUI or terminal Vim?

**Comment by CryDeTaan** [comment]
I am using terminal vim.
SSH from mac(iTerm) to a CentOS 7 server

**Comment by tjbcg** [comment]
Using neovim (tested with vim too) in a terminal. The same bug applies for different values of TERM, and with or without ssh.

Have a look at the `hi-normal` help page. It states that vim can guess wrongly when in a terminal. I think the patch is sufficient enough to force vim into not making any mistake.

**Comment by josuegaleas** [comment]
Sorry for the delay, I've pushed the fix that @FliiFe suggested. See if that helps you all.

I was unable to replicate the error on my end, but `hi-normal-cterm` does suggest that such an issue could exist. I will leave this open in case issues still persist.

**Comment by CryDeTaan** [comment]
Thanks, it did the trick

**Comment by CryDeTaan** [comment]
Actually, it seems it does not work on CentOS. Works on my Mac though.

**Comment by tjbcg** [comment]
@CryDeTaan That's strange... the fix should be forcing the background value. Can you test with no other plugin than this colorscheme ? Also, are you sure you are correctly setting `background=dark` before applying the colorscheme ?

**Comment by CryDeTaan** [comment]
Yes, I use a dotfile repo on all my machines. 

https://github.com/CryDeTaan/dotfiles/blob/master/dotfiles.d/vimrc.d/02-JayColorscheme.vim

**Comment by josuegaleas** [comment]
Hmm, what version of Vim are you guys running? I'm running 8.0.771. It's unlikely, but maybe it's an issue with Vim that has been addressed in later versions/patches?

**Comment by CryDeTaan** [comment]
On CentOS(where it not working)
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 21 2016 17:00:20) Included patches: 1-160

On MacOS(Where it works perfectly) 
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54) Included patches: 1-898, 8056

**Comment by tjbcg** [comment]
I use neovim 2.0, tested with vim 8 (can't remember the exact version :-/).

**Comment by josuegaleas** [comment]
> On CentOS(where it not working) VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 21 2016 17:00:20) Included patches: 1-160

This may seem ridiculous after all this time but I have been revising this colorscheme for a small update coming soon and I wanted to settle this issue. I tried replicating the CentOS environment [as close as possible](https://vault.centos.org/7.4.1708/isos/x86_64/) in a VM and did not have an issue with the background being reset to "light" with the fix @FliiFe suggested many years ago. As you can see down below, the Vim version is the same with the same patches albeit complied at a later date. The `vimrc` sets the background and the colorscheme and echos the value of `&background` which outputs "dark" as expected. I also tested it by setting the background to "light" and it also worked as expected.

![{E5AB800D-4BAF-4E9A-A3C2-100B9077DA0F}](https://github.com/user-attachments/assets/1a535851-2fb3-479b-84f7-13712e84998b)

I can't explain (especially not after all this time) why it wasn't working on your CentOS server @CryDeTaan. Perhaps I am using a slightly different version of CentOS 7? Perhaps the compilation date of the Vim install makes the difference? By now I'm sure you've moved on to a newer version of Vim or something else entirely. Thank you all for using my colorscheme, even if you don't use it anymore.

As an aside, in newer versions of Vim (no idea when it was fixed or changed), it *seems* it's no longer needed to refresh the value of the background. However, the help page for `hi-normal-cterm` still makes mention of it being reset like before so I'm just going to play it safe and leave the fix in permanently. Furthermore, it keeps the colorscheme backwards compatible for anyone still using Vim 7.4 and possibly older.

**Comment by tjbcg** [comment]
I have little recollection of debugging this, but to be fair it seems likely that this was fix at vim level at some point since my "fix" does look a lot like a workaround and a bit hack-y.

It's also probably a reasonable assumption that no one is voluntarily using vim 7 anymore. While I've now moved to another colorscheme entirely, I remember jay fondly and have used it for many years (by the looks of it, at least four). I wish you the best for your future endeavors with this project and others ;-)
