### ISSUE TITLE
Lightline tabbar 

### ISSUE THREAD

**Issue by ksergey** [josuegaleas/jay#5]
Hi,

Could you please fix lightline colorscheme for tabbar? It's looks like not so contrast for me or something like that.

![issue](https://i.imgur.com/5CB0q20.png)

Thanks

**Comment by josuegaleas** [comment]
I've never been perfectly happy with how the tabline is in the Airline and Lightline themes, I'll see what I can do.

**Comment by josuegaleas** [comment]
@ksergey What do you think of this?

<img width="528" alt="screen shot 2017-10-06 at 11 26 12 pm" src="https://user-images.githubusercontent.com/13757382/31305398-c6a1f354-aaed-11e7-8556-e6f221360424.png">

**Comment by josuegaleas** [comment]
For those that are curious about this change but for Airline, look here:

<img width="732" alt="screen shot 2017-10-07 at 7 34 07 pm" src="https://user-images.githubusercontent.com/13757382/31313385-9a8102d4-ab96-11e7-84db-99ca8c4e889f.png">

**Comment by ksergey** [comment]
@josuegaleas Looks very good!

**Comment by josuegaleas** [comment]
Good to hear! I will push out an update some time today or tomorrow.

**Comment by ksergey** [comment]
Looking forward for update!
